RoleProject/Models/RolesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RoleProject.Models
{
    public class RolesViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }

    }
}

RoleProject/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using RoleProject.Models;
using RoleProject.View_Model;

namespace RoleProject.Controllers
{


    public class CarsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        [AllowAnonymous]


        public ActionResult List_Of_All()
        {
            try
            {
                var cars = new List<Car>();

                if (User.IsInRole("Agince"))
                {
                    string id = User.Identity.GetUserId();

                    cars = (from w in db.Cars
                            where w.Agince_Of_Car.Agince_ID == id
                            select w).ToList();

                }
                else
                {


                    cars = db.Cars.ToList();

                }

                return View(cars);
            }
            catch (Exception)
            {

                return RedirectToAction("error", "HomeFolder");
            }


        }

        public ActionResult List_of_Car_inowner_Agince(string id)
        {
            try
            {
                var cars = (from w in db.Cars
                            where w.Agince_Of_Car.Agince_ID == id
                            select w).ToList();


                return View("List_Of_All", cars);
            }
            catch (Exception)
            {

                return RedirectToAction("error", "HomeFolder");
            }


        }



        [AllowAnonymous]

        public ActionResult filter()
        {
            try
            {
                return PartialView("_filter_Car", db.Car_properties.ToList());
            }
            catch (Exception)
            {

                return RedirectToAction("error", "HomeFolder");
            }

        }
        [AllowAnonymous]

        public ActionResult go_filter(String prop_name)
        {
            try
            {
                var carstemp = TempData["cars"] as List<Car>;
                int prop_id = db.Car_properties.FirstOrDefault(e => e.proprity_Name == prop_name).id;


                var carsIds = (from e in db.Car_And_Properites
                               where e.id == prop_id
                               select e.Car_Id).ToList();

                List<Car> cars = new List<Car>();
                foreach (var item in carsIds)
                {
                    Car res = db.Cars.FirstOrDefault(e => e.Car_Id == item);
                    cars.Add(res);

                }

                return View("List_Of_all", cars);
            }
            catch (Exception)
            {

                return RedirectToAction("error", "HomeFolder");
            }




        }
        // search
        [AllowAnonymous]

        public ActionResult Search()
        {

            try
            {
                return PartialView("_Search_Car_Partial");
            }
            catch (Exception)
            {

                return RedirectToAction("error", "HomeFolder");
            }


        }

        [AllowAnonymous]


        public ActionResult Go_Search(string type, string brand, string model_ofCar, int? price)
        {
            try
            {
                List<Car> cars = db.Cars.Where(x => x.Type_Of_Car.Contains(type) && x.Car_Brand.Contains(brand)
           && x.Car_Model.Contains(model_ofCar) && x.price_in_day <= price).ToList();

                return View("List_Of_All", cars);
            }
            catch (Exception)
            {

                return RedirectToAction("error", "HomeFolder");
            }




        }

        //// search
        [AllowAnonymous]

        public ActionResult Search_By_Chassia()
        {
            try
            {
                return PartialView("_Search_Car_By_Chassia_Partial");
            }
            catch (Exception)
            {

                return RedirectToAction("error", "HomeFolder");
            }



        }
        [AllowAnonymous]


        public ActionResult Go_Search_By_Chassia(string Chassis, string type, string model, string brand)/*, int? num)*/
        {
            try
            {
                List<Car> cars = db.Cars.Where(x => x.Chassis_No == Chassis && x.Car_Model.Contains(model) && x.Car_Brand.Contains(brand) | x.Type_Of_Car.Contains(type)).ToList();

                if (cars != null)
                    return View("List_Of_All", cars);
                else
                    return View("List_Of_All", db.Cars.ToList());

            }
            catch (Exception)
            {

                return RedirectToAction("error", "HomeFolder");
            }








        }
        [AllowAnonymous]


        public ActionResult sorting()
        {
            try
            {
                return PartialView("_Sorting_Partial");
            }
            catch (Exception)
            {

                return RedirectToAction("error", "HomeFolder");
            }

        }
        [AllowAnonymous]


        public ActionResult Go_sorting(int? num)
        {
            try
            {

                if (num == null)
                {

                    return View("List_Of_All", db.Cars.ToList());


                }

                else

                {

                    var cars = new List<Car>();

                    var carstemp = TempData["cars"] as List<Car>;


                    switch (num)
                    {

                        case 1:
                            cars = carstemp.OrderBy(e => e.price_in_day).ToList();
                            break;
                        case 2:
                            cars = carstemp.OrderByDescending(e => e.price_in_day).ToList();
                            break;
                        case 3:
                            cars = carstemp.OrderBy(e => e.Car_Brand).ToList();
                            break;

                        case 4:
                            cars = carstemp.OrderBy(e => e.Car_Model).ToList();
                            break;
                        case 5:
                            cars = carstemp.OrderByDescending(e => e.Car_Model).ToList();
                            break;


                    }



                    return View("List_Of_All", cars);
                }
            }
            catch (Exception)
            {

                return RedirectToAction("error", "HomeFolder");
            }


        }


        [AllowAnonymous]


        public ActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return RedirectToAction("error", "HomeFolder");
                }
                Car car = db.Cars.FirstOrDefault(Car_ => Car_.Car_Id == id);
                cars_and_properties cars_And_Properties = new cars_and_properties();

                cars_And_Properties.Property_Name =
                    (from car_ in db.Car_And_Properites
                     where (car_.Cars.Car_Id == car.Car_Id)
                     select (
                     car_.properties.proprity_Name
                            )).ToList();

                Dates_For_Car Date = new Dates_For_Car();
                Date.Start_Recive = (from Dates in db.ReciveDates
                                     where (Dates.cars.Car_Id == car.Car_Id)
                                     select
                                     (
                                        Dates.Start_Recive_Date
                                         )).ToList();
                Date.End_Recive = (from Dates in db.ReciveDates
                                   where (Dates.cars.Car_Id == car.Car_Id)
                                   select
                                   (
                                      Dates.End_Recive_Date
                                       )).ToList();
                Date.Clients = (from Dates in db.ReciveDates
                                where (Dates.cars.Car_Id == car.Car_Id)
                                select
                                (
                                   Dates.client
                                    )).ToList();
                Agince agince = (from ca in db.Cars
                                 from ag in db.Agince
                                 where (ag.Agince_ID == ca.Agince_Of_Car.Agince_ID)
                                 select (ag)).FirstOrDefault();

                ViewBag.Agince = agince;
                ViewBag.list_of_Recived_Date = Date;
                ViewBag.list_of_properties = cars_And_Properties;
                ViewBag.Allcars = db.Cars.Take(8).ToList();


                if (car == null)
                {
                    return RedirectToAction("error", "HomeFolder");
                }
                return View(car);
            }
            catch (Exception)
            {

                return RedirectToAction("error", "HomeFolder");
            }

        }



        [Authorize(Roles = "Agince")]

        public ActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {

                return RedirectToAction("error", "HomeFolder");
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Agince")]

        public ActionResult Create(Car car)
        {
            try
            {
                string Agince_ID = User.Identity.GetUserId();
                Agince agince = db.Agince.FirstOrDefault(agince_ => agince_.Agince_ID == Agince_ID);
                if (car.photo_path != null)
                {
                    string filename = Path.GetFileNameWithoutExtension(car.photo_path.FileName);

RoleProject/Controllers/RolesController.cs
using Microsoft.AspNet.Identity.EntityFramework;
using RoleProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RoleProject.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RolesController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        public ActionResult List_Of_All()
        {
            return View(context.Roles.ToList());
        }


        public ActionResult Details(string id)
        {

            var role = context.Roles.Find(id);
            if (role == null) {
                return HttpNotFound();
            }
            else

            return View(role);
        }


        public ActionResult Create()
        {
            return View(new IdentityRole());
        }


        [HttpPost]
        public ActionResult Create(IdentityRole role)
        {



            if (ModelState.IsValid)
            {
                context.Roles.Add(role);
                context.SaveChanges();
                return RedirectToAction("List_Of_All");
            }
            else { return View(role); }

        }


        public ActionResult Edit(string id)
        {
            var role = context.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            else
                return View(role);
        }


        [HttpPost]
        public ActionResult Edit(string id, IdentityRole role)
        {

            if (ModelState.IsValid)
            {
                IdentityRole thenew = context.Roles.Find(id);
                thenew.Id = role.Id;
                thenew.Name = role.Name;
                context.SaveChanges();
                return RedirectToAction("List_Of_All");
            }
            else { return View(role); }



        }


        public ActionResult Delete(string id)
        {
            var role =context.Roles.FirstOrDefault(e => e.Id == id);
            if (role == null)
            {
                return HttpNotFound();
            }
            else
                return View(role);
        }


        [HttpPost]
        public ActionResult Delete(IdentityRole role)
        {

            if (ModelState.IsValid)
            {
                IdentityRole role_del = context.Roles.Find(role.Id);
                context.Roles.Remove(role_del);
                context.SaveChanges();
                return RedirectToAction("List_Of_All");
            }
            else { return View(role); }

        }
    }
}

RoleProject/Views/Roles/Create.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

@{
    ViewBag.Title = "Create";
}





<div class="hero-wrap" style="background-image: url('/Content/autoroad/images/bg_1.jpg');height:1000px" data-stellar-background-ratio="0.5">
    <div class="overlay" style="height:1000px"></div>
    <div class="container">
        <div class="row no-gutters slider-text justify-content-start align-items-center">
            <div class="col-lg-6 col-md-6 ftco-animate d-flex align-items-end">
                <div class="text">
                    <h1 class="mb-4">Welcom <span>In your Agince Website</span> <span></span></h1>
                    @Html.ActionLink("Back ", "List_Of_All", "Cars", null, htmlAttributes: new { @class = "btn btn-primary" })
                </div>
            </div>
            <div class="col-lg-2 col"></div>
            <div class="col-lg-4 col-md-6 mt-0 mt-md-5 d-flex">
             



                @using (Html.BeginForm("create","Roles",FormMethod.Post,htmlAttributes:new {    @class = "request-form ftco-animate "}))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Create new Role</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RoleProject/Views/Roles/Delete.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

@{
    ViewBag.Title = "Delete";
}




<div class="hero-wrap" style="background-image: url('/Content/autoroad/images/bg_1.jpg');height:1000px" data-stellar-background-ratio="0.5">
    <div class="overlay" style="height:1000px"></div>
    <div class="container">
        <div class="row no-gutters slider-text justify-content-start align-items-center">
            <div class="col-lg-6 col-md-6 ftco-animate d-flex align-items-end">
                <div class="text">
                    <h1 class="mb-4">Are you sure you want to delete this?</span></h1>
                    @Html.ActionLink("Back ", "List_Of_All", "Cars", null, htmlAttributes: new { @class = "btn btn-primary" })
                </div>
            </div>
            <div class="col-lg-2 col"></div>
            <div class="col-lg-4 col-md-6 mt-0 mt-md-5 d-flex">




                @using (Html.BeginForm("Delete", "Roles", FormMethod.Post, htmlAttributes: new { @class = "request-form ftco-animate " }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Delete Role</h4>
                        <hr />
                   
                    <div class="form-group">
                        <span style="font-weight:bold">
                            @Html.DisplayNameFor(model => model.Name)
                        </span>
                            @Html.DisplayFor(model => model.Name)
                    </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Delete" class="btn btn-primary" />
                            </div>
                        </div>
                 
                }

            </div>
        </div>
    </div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RoleProject/Views/Roles/List_Of_All.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>

@{
    ViewBag.Title = "Index";
}




  


<div class="hero-wrap" style="background-image: url('/Content/autoroad/images/bg_1.jpg');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text justify-content-start align-items-center">
            <div class="col-lg-6 col-md-6 ftco-animate d-flex align-items-end">
                <div class="text">
                    <h1 class="mb-4">Car Details</h1>
                    @Html.ActionLink("Back ", "List_Of_All", "Cars", null, htmlAttributes: new { @class = "btn btn-primary" })
                    @Html.ActionLink("Create New", "Create", null, htmlAttributes: new { @class = "btn btn-primary" })
                </div>
            </div>
            <div class="col-lg-2 col"></div>
            <div class="col-lg-4 col-md-6 mt-0 mt-md-5 d-flex">
                <form action="#" class="request-form ftco-animate" style="width:200px">

                    <table class="table table-hover">


                        <h3> Name</h3>





                        @foreach (var item in Model)
                        {
                    <tr>
                      
                            @Html.DisplayFor(Item => item.Name)
   
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-primary" })
                      <hr/>
                    </tr>
                         
                        }

                    </table>

                </form>
            </div>
        </div>
    </div>
</div>